# Generated by Django 4.0.2 on 2022-11-19 18:50

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroConsultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroEspecialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissional', models.CharField(max_length=100)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areadeservicos.cadastroconsultas')),
            ],
        ),
        migrations.CreateModel(
            name='DadosPreAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomecompleto', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nomecompleto', unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=11)),
                ('dtnascimento', models.DateField()),
                ('obs', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPreAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areadeservicos.cadastroprofissional')),
                ('dadosagenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areadeservicos.dadospreagenda')),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadeAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('agenda_especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areadeservicos.cadastroespecialidades')),
                ('dadosagenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areadeservicos.dadospreagenda')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areadeservicos.cadastroconsultas')),
                ('dadosagenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areadeservicos.dadospreagenda')),
            ],
        ),
        migrations.AddField(
            model_name='cadastroespecialidades',
            name='profissional_esp',
            field=models.ManyToManyField(blank=True, to='areadeservicos.CadastroProfissional'),
        ),
    ]
